package com.hand.exam.censu.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "hap_sub_census")
public class Censu extends BaseDTO {

     public static final String FIELD_LINE_ID = "lineId";
     public static final String FIELD_ORDER_NUMBER = "orderNumber";
     public static final String FIELD_COMPANY_NAME = "companyName";
     public static final String FIELD_CUSTOMER_NAME = "customerName";
     public static final String FIELD_ORDER_DATE = "orderDate";
     public static final String FIELD_ORDER_STATUS = "orderStatus";
     public static final String FIELD_ITEM_CODE = "itemCode";
     public static final String FIELD_ITEM_DESCRIPTION = "itemDescription";
     public static final String FIELD_ORDERD_QUANTITY = "orderdQuantity";
     public static final String FIELD_UNIT_SELLING_PRICE = "unitSellingPrice";


     @Id
     @GeneratedValue
     private Long lineId; //公司ID

     @NotEmpty
     @Length(max = 60)
     private String orderNumber; //订单编号

     @NotEmpty
     @Length(max = 240)
     private String companyName; //公司名称

     @NotEmpty
     @Length(max = 240)
     private String customerName; //客户名称

     private Date orderDate; //订单日期

     @NotEmpty
     @Length(max = 30)
     private String orderStatus; //订单状态

     @NotEmpty
     @Length(max = 60)
     private String itemCode; //物料编码

     @NotEmpty
     @Length(max = 240)
     private String itemDescription; //物料描述

     @NotNull
     private Long orderdQuantity; //数量

     @NotNull
     private Long unitSellingPrice; //销售单价


     public void setLineId(Long lineId){
         this.lineId = lineId;
     }

     public Long getLineId(){
         return lineId;
     }

     public void setOrderNumber(String orderNumber){
         this.orderNumber = orderNumber;
     }

     public String getOrderNumber(){
         return orderNumber;
     }

     public void setCompanyName(String companyName){
         this.companyName = companyName;
     }

     public String getCompanyName(){
         return companyName;
     }

     public void setCustomerName(String customerName){
         this.customerName = customerName;
     }

     public String getCustomerName(){
         return customerName;
     }

     public void setOrderDate(Date orderDate){
         this.orderDate = orderDate;
     }

     public Date getOrderDate(){
         return orderDate;
     }

     public void setOrderStatus(String orderStatus){
         this.orderStatus = orderStatus;
     }

     public String getOrderStatus(){
         return orderStatus;
     }

     public void setItemCode(String itemCode){
         this.itemCode = itemCode;
     }

     public String getItemCode(){
         return itemCode;
     }

     public void setItemDescription(String itemDescription){
         this.itemDescription = itemDescription;
     }

     public String getItemDescription(){
         return itemDescription;
     }

     public void setOrderdQuantity(Long orderdQuantity){
         this.orderdQuantity = orderdQuantity;
     }

     public Long getOrderdQuantity(){
         return orderdQuantity;
     }

     public void setUnitSellingPrice(Long unitSellingPrice){
         this.unitSellingPrice = unitSellingPrice;
     }

     public Long getUnitSellingPrice(){
         return unitSellingPrice;
     }

     }
